### ISSUE TITLE
Getting HTTP 400:{"error":"invalid_request"} when clicking on Oauth request url

### ISSUE THREAD

**Issue by booyaa** [pnelson/moves#1]
I've tried to use your example code in your readme: https://github.com/pnelson/moves/blob/master/README.md#usage. I used the example that requires your client id and secret (replaced it with my own dev secrets) to obtain the initial token.

Here's the output from my test code:

```
Enter the following URL in your browser.
https://api.moves-app.com/oauth/v1/authorize?client_id=MY_CLIENT_IDx&response_type=code&scope=activity+location&state=foo
Follow the instructions in the browser.
When your browser redirects, grab the code from the query string.
Paste the code here:
```

Is there anything I needed to change for the example code to work?

**Comment by pnelson** [comment]
At that point if you copy the URL to your browser you should see something like this:

```
To allow <app_name> to use your data

Open Moves on your phone
Choose main menu > Connected Apps > Enter PIN
Enter code
<eight_digit_code>
```

Did you get to that point?

If you follow those steps and enter the displayed eight digit PIN/code on the phone app, the page should automatically redirect to your application Redirect URI with the query parameter `?code=<authorization_code>`. If you copy the `authorization_code` to the terminal prompt, it should proceed.

Let me know how that goes.

**Comment by booyaa** [comment]
When I paste the url into my browser that's when I get this message: {"error":"invalid_request"} 

Does the `state` parameter (currently foo) need to match my application name?

**Comment by pnelson** [comment]
Weird. No, `state` is an OAuth security thing. It is optional, though recommended. `foo` is fine for a placeholder for now though.

I just created a new test app and I get a URL that works. You won't be able to complete the flow with this link since you don't have my secret but any valid client id should get past the first step.

https://api.moves-app.com/oauth/v1/authorize?client_id=V93W_NS9mwd86QSmvU9Q4j2m1wa7p363&response_type=code&scope=activity+location&state=foo

Are you sure you didn't miss a character when you copied your client id? Does my link work for you to at least pass the first step?

**Comment by booyaa** [comment]
Gave that link a go and I trigger an error during the t.Exchange(code):

```
err: invalid_grant
```

I even tried regenerating the secret to no avail.

I've created a temporary application and stuck a gist with my test code (which also exhibits the same problem).

https://gist.github.com/booyaa/a6de31ade7be3999ab46

I've embedded the client id and secret (it's a throw away app so I'll delete it after we've finished testing).

Just wanted to check application setup, I've not populated of the fields in the development tab of the application. Did I need to fill out any of the redirect uris fields? In fact asides the mandatory information I've not entered anything else for the application.

**Comment by pnelson** [comment]
I cloned your gist and was able to replicate the issue. Replacing your client id/secret with mine works. You need to specify the first _Redirect URI_ on the _Development_ tab of your app. I confirmed by removing it from mine and replicating the issue with my keys. Give that a try and let me know how it goes.

I'll update my README. Thanks for the feedback. I'd be interested in seeing what you build with this when you're done.

Edit: I discovered some other issues past that point. Admittedly, I haven't touched this in almost a year. I'll take a look and update when safe to bother proceeding.

Edit 2: I just don't handle errors as well as I should. I'll create a separate issue but in the example you provided, you'll need to use a date in which your account has data for.

**Comment by booyaa** [comment]
Redirect URI resolved this error! Thanks. I'm still getting the invalid_grant error, but I think that warrants more investigation by me and at least a different issue.

Thanks again for you help. I'm going to use your go library to drive my own project called https://github.com/booyaa/dthulhu which aggregates data from various sources into your Day One personal journal.

**Comment by stevenqzhang** [comment]
I just had the same issue. I'm glad this issue was filed, because the moves official documentation is not clear about the need to fill out the redirect URI
